import { chromium } from '../frontend/node_modules/playwright/index.mjs';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
await mkdir(path.join(root,'docs/assets'),{recursive:true});
const browser=await chromium.launch({channel:'msedge'});
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:path.join(root,'outputs/video'),size:{width:1440,height:1000}}});
const page=await context.newPage();
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const start=Date.now();
await page.goto('http://127.0.0.1:5174');
await page.getByRole('button',{name:'Run MCP demo',exact:true}).waitFor();
await page.waitForTimeout(2000);
await page.getByRole('button',{name:'Run MCP demo',exact:true}).click();
await page.locator('.detail .status').first().filter({hasText:'succeeded'}).waitFor({timeout:30000});
await page.screenshot({path:path.join(root,'docs/assets/trace.png')});
await page.waitForTimeout(2200);
await page.getByRole('tab',{name:'Diff',exact:true}).click();
await page.screenshot({path:path.join(root,'docs/assets/diff.png')});
await page.waitForTimeout(3500);
await page.getByRole('tab',{name:'Verification',exact:true}).click();
await page.waitForTimeout(3000);
await page.getByRole('tab',{name:'Context',exact:true}).click();
await page.waitForTimeout(3000);
await page.getByRole('button',{name:'Evaluation',exact:true}).click();
await page.getByText('36 / 36',{exact:true}).waitFor();
await page.waitForTimeout(2500);
await page.getByRole('heading',{name:'Five configuration wiring checks on a known fixture'}).scrollIntoViewIfNeeded();
await page.waitForTimeout(3000);
await page.getByRole('button',{name:'Memory',exact:true}).click();
await page.waitForTimeout(2500);
await page.getByRole('button',{name:'Overview',exact:true}).click();
await page.waitForTimeout(Math.max(0,30000-(Date.now()-start)));
const video=page.video();
await context.close();
await video.saveAs(path.join(root,'docs/assets/demo.webm'));
await browser.close();
await writeFile(path.join(root,'docs/assets/demo-recording.json'),JSON.stringify({kind:'actual-local-browser-recording',provider:'deterministic-fake',transport:'MCP stdio with native patch',recording_wall_time_ms:Date.now()-start,page_errors:errors,model_performance_claim:false},null,2));
if(errors.length)process.exitCode=1;
console.log(JSON.stringify({duration_ms:Date.now()-start,errors}));
